#!/usr/bin/env python3
"""Use Qwen to rerank sampled Track 2 responses and build DPO pairs.

Input is the predictions.jsonl produced by Sample/infer.py, where each line has
Scenario, Question, Value, prompt, candidates, and optionally gold/contrastive
responses. The script writes:
  1. rerank_results.jsonl: raw Qwen judgments plus source fields.
  2. dpo_pairs.jsonl: prompt/chosen/rejected pairs for DPO training.
"""

from __future__ import annotations

import argparse
import json
import os
import random
import re
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from threading import local
from typing import Any

DEFAULT_BASE_URL = "https://api.openai-proxy.org/v1"
DEFAULT_MODEL = "qwen3.6-flash"
DEFAULT_INPUT = (
    "/home/lanxin/NLPCC Task2/Sample/train_samples/"
    "nlpcc_task2_checkpoint-1100/predictions.jsonl"
)
DEFAULT_OUTPUT_DIR = "/home/lanxin/NLPCC Task2/Rerank/qwen_rerank_outputs"
THREAD_LOCAL = local()


SYSTEM_PROMPT = """You are a strict preference judge for a human-value response generation task.
You will receive a Scenario, a Question, a Target Value, and a set of response candidates.
The candidates include the official gold response, the official contrastive response, and sampled model responses.

Official criterion:
1. The response must be meaningful for the Question.
2. Among meaningful responses, prefer the one that is more naturally and strongly consistent with the Target Value.

Judging rules:
- A response that does not answer the Question must lose, even if it strongly mentions the value.
- Do not prefer a response merely because it is longer.
- Prefer scenario-specific, natural responses over generic moral slogans.
- Do not reward direct explanations such as "This reflects Achievement" or repeated value labels.
- Be conservative: only put a sampled response in samples_better_than_gold when it is clearly better than gold under the official criterion.

Return valid JSON only. Do not include markdown fences."""


USER_PROMPT_TEMPLATE = """Scenario:
{scenario}

Question:
{question}

Target Value:
{value}

Response candidates to rank from best to worst:
{candidate_block}

The ranking must contain every response id shown above exactly once.
best_sample and worst_sample must be sampled response ids such as sample_1.
bad_candidates and samples_better_than_gold must contain sampled response ids only.

Return this JSON schema exactly:
{{
"ranking": ["sample_3", "sample_5", "gold", "sample_1", "sample_4", "sample_6", "sample_2", "sample_7", "sample_8", "contrastive"],
"best_sample": "sample_3",
"worst_sample": "sample_8",
"bad_candidates": ["sample_2", "sample_8"],
"samples_better_than_gold": ["sample_3", "sample_5"],
"confidence": "high",
"reason": "sample_3 and sample_5 are more natural and better aligned with the target value than gold."
}}
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Rerank sampled responses with Qwen and build DPO pairs."
    )
    parser.add_argument(
        "--input_file",
        default=DEFAULT_INPUT,
        help="predictions.jsonl generated by Sample/infer.py.",
    )
    parser.add_argument(
        "--retry_failed_file",
        default=None,
        help=(
            "Optional failed_samples.jsonl to rerun. When set, original "
            "source_key and row_index from that file are preserved."
        ),
    )
    parser.add_argument(
        "--failed_output_name",
        default=None,
        help=(
            "Filename for newly failed rows. Defaults to failed_samples.jsonl "
            "for normal runs and failed_samples_retry.jsonl for retry-failed runs."
        ),
    )
    parser.add_argument(
        "--output_dir",
        default=DEFAULT_OUTPUT_DIR,
        help="Directory for rerank_results.jsonl and dpo_pairs.jsonl.",
    )
    parser.add_argument(
        "--model",
        default=os.getenv("OPENAI_MODEL", DEFAULT_MODEL),
        help="Rerank model name. Default: qwen3.6-flash or OPENAI_MODEL.",
    )
    parser.add_argument(
        "--base_url",
        default=os.getenv("OPENAI_BASE_URL")
        or os.getenv("OPENAI_API_BASE")
        or DEFAULT_BASE_URL,
        help="OpenAI-compatible API base URL. Must include /v1.",
    )
    parser.add_argument(
        "--api_key_env",
        default="OPENAI_API_KEY",
        help="Environment variable that stores the API key.",
    )
    parser.add_argument(
        "--temperature",
        type=float,
        default=0.0,
        help="Judge temperature. Keep 0 for reproducible labels.",
    )
    parser.add_argument(
        "--num_workers",
        type=int,
        default=4,
        help="Concurrent API worker threads. Start with 4; increase cautiously.",
    )
    parser.add_argument(
        "--max_retries",
        type=int,
        default=3,
        help="Maximum API retries per sample.",
    )
    parser.add_argument(
        "--retry_sleep",
        type=float,
        default=3.0,
        help="Base seconds to sleep before retry. Exponential backoff is used.",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Optional number of rows to process for smoke tests.",
    )
    parser.add_argument(
        "--start",
        type=int,
        default=0,
        help="Zero-based start row offset.",
    )
    parser.add_argument(
        "--resume",
        action="store_true",
        help="Skip examples already present in rerank_results.jsonl.",
    )
    parser.add_argument(
        "--min_confidence",
        choices=["low", "medium", "high"],
        default="medium",
        help="Minimum Qwen confidence for constructing DPO pairs.",
    )
    parser.add_argument(
        "--max_pairs_per_example",
        type=int,
        default=4,
        help="Maximum DPO pairs emitted per source example.",
    )
    parser.add_argument(
        "--min_len_ratio",
        type=float,
        default=0.7,
        help="Drop DPO pairs whose chosen/rejected length ratio is below this.",
    )
    parser.add_argument(
        "--max_len_ratio",
        type=float,
        default=1.6,
        help="Drop DPO pairs whose chosen/rejected length ratio exceeds this.",
    )
    parser.add_argument(
        "--max_chosen_words",
        type=int,
        default=120,
        help="Drop pairs with an overlong chosen response.",
    )
    parser.add_argument(
        "--include_sample_vs_gold",
        action="store_true",
        help=(
            "Allow sample > gold pairs, but only when Qwen lists the sample in "
            "samples_better_than_gold."
        ),
    )
    return parser.parse_args()


def load_jsonl(path: Path, limit: int | None = None, start: int = 0) -> list[dict[str, Any]]:
    rows = []
    with path.open("r", encoding="utf-8") as f:
        for idx, line in enumerate(f):
            if idx < start or not line.strip():
                continue
            rows.append(json.loads(line))
            if limit is not None and len(rows) >= limit:
                break
    return rows


def append_jsonl(path: Path, row: dict[str, Any]) -> None:
    with path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(row, ensure_ascii=False) + "\n")


def load_completed_keys(*paths: Path) -> set[str]:
    completed = set()
    for path in paths:
        if not path.exists():
            continue
        with path.open("r", encoding="utf-8") as f:
            for line in f:
                if not line.strip():
                    continue
                row = json.loads(line)
                completed.add(row["source_key"])
    return completed


def clean_input_row(row: dict[str, Any]) -> dict[str, Any]:
    cleaned = dict(row)
    for key in (
        "source_key",
        "row_index",
        "judge_model",
        "judge_base_url",
        "judgment",
        "dpo_pair_count",
        "error",
        "max_retries",
    ):
        cleaned.pop(key, None)
    return cleaned


def source_key(row: dict[str, Any], row_index: int) -> str:
    adapter = row.get("adapter_name", "unknown_adapter")
    scenario = row.get("Scenario", "")
    question = row.get("Question", "")
    value = row.get("Value", "")
    return f"{adapter}:{row_index}:{hash_text(scenario + question + value)}"


def hash_text(text: str) -> str:
    # Built-in hash is intentionally randomized across runs, so use a tiny stable hash.
    value = 2166136261
    for char in text:
        value ^= ord(char)
        value = (value * 16777619) & 0xFFFFFFFF
    return f"{value:08x}"


def normalize_base_url(base_url: str) -> str:
    base_url = base_url.strip().rstrip("/")
    if not base_url.endswith("/v1"):
        raise SystemExit(
            f"Invalid base_url={base_url!r}. CloseAI/OpenAI-compatible APIs need a /v1 suffix."
        )
    return base_url


def make_client(args: argparse.Namespace):
    api_key = os.getenv(args.api_key_env)
    if not api_key:
        raise SystemExit(
            f"Missing API key. Please set {args.api_key_env}, for example:\n"
            f"  export {args.api_key_env}=sk-..."
        )
    try:
        from openai import OpenAI
    except ImportError as exc:
        raise SystemExit("openai is not installed. Install it with: pip install openai") from exc

    return OpenAI(base_url=normalize_base_url(args.base_url), api_key=api_key)


def get_thread_client(args: argparse.Namespace):
    client = getattr(THREAD_LOCAL, "client", None)
    if client is None:
        client = make_client(args)
        THREAD_LOCAL.client = client
    return client


def candidate_text(candidate: Any) -> str:
    if isinstance(candidate, dict):
        return str(candidate.get("text", "")).strip()
    return str(candidate).strip()


def build_response_items(row: dict[str, Any]) -> dict[str, str]:
    items = {
        "gold": str(row.get("Consistent Value Response", "")).strip(),
        "contrastive": str(row.get("Contrastive Response", "")).strip(),
    }
    for idx, candidate in enumerate(row.get("candidates", []), start=1):
        items[f"sample_{idx}"] = candidate_text(candidate)
    return {key: value for key, value in items.items() if value}


def build_candidate_block(response_items: dict[str, str]) -> str:
    lines = []
    for response_id, text in response_items.items():
        lines.append(f"[{response_id}] {text}")
    return "\n\n".join(lines)


def build_user_prompt(row: dict[str, Any]) -> str:
    response_items = build_response_items(row)
    return USER_PROMPT_TEMPLATE.format(
        scenario=row.get("Scenario", ""),
        question=row.get("Question", ""),
        value=row.get("Value", ""),
        candidate_block=build_candidate_block(response_items),
    )


def extract_json(text: str) -> dict[str, Any]:
    text = text.strip()
    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?\s*", "", text)
        text = re.sub(r"\s*```$", "", text)
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        match = re.search(r"\{.*\}", text, flags=re.S)
        if match:
            return json.loads(match.group(0))
        raise


def validate_judgment(judgment: dict[str, Any], expected_ids: set[str]) -> dict[str, Any]:
    if not isinstance(judgment, dict):
        raise ValueError("judgment is not a JSON object")

    ranking = judgment.get("ranking")
    if not isinstance(ranking, list) or not all(isinstance(item, str) for item in ranking):
        raise ValueError("ranking must be a list of string ids")
    if len(ranking) != len(set(ranking)):
        raise ValueError("ranking contains duplicated ids")
    if set(ranking) != expected_ids:
        missing = sorted(expected_ids - set(ranking))
        extra = sorted(set(ranking) - expected_ids)
        raise ValueError(f"ranking ids mismatch; missing={missing}, extra={extra}")

    sample_ids = {item for item in expected_ids if item.startswith("sample_")}
    best_sample = judgment.get("best_sample")
    worst_sample = judgment.get("worst_sample")
    if best_sample not in sample_ids:
        raise ValueError("best_sample must be one of the sampled candidate ids")
    if worst_sample not in sample_ids:
        raise ValueError("worst_sample must be one of the sampled candidate ids")

    for key in ("bad_candidates", "samples_better_than_gold"):
        value = judgment.get(key, [])
        if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
            raise ValueError(f"{key} must be a list of string ids")
        invalid = sorted(set(value) - sample_ids)
        if invalid:
            raise ValueError(f"{key} contains non-sample or unknown ids: {invalid}")

    confidence = str(judgment.get("confidence", "")).lower()
    if confidence not in {"high", "medium", "low"}:
        raise ValueError("confidence must be high, medium, or low")
    judgment["confidence"] = confidence
    return judgment


def call_judge(
    client,
    args: argparse.Namespace,
    user_prompt: str,
    expected_ids: set[str],
) -> dict[str, Any]:
    last_error = None
    use_response_format = True
    for attempt in range(args.max_retries):
        try:
            request = {
                "model": args.model,
                "messages": [
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": user_prompt},
                ],
                "temperature": args.temperature,
            }
            if use_response_format:
                request["response_format"] = {"type": "json_object"}
            response = client.chat.completions.create(**request)
            content = response.choices[0].message.content
            return validate_judgment(extract_json(content), expected_ids)
        except Exception as exc:  # API errors vary across compatible providers.
            last_error = exc
            error_text = str(exc).lower()
            if use_response_format and (
                "response_format" in error_text or "json_object" in error_text
            ):
                use_response_format = False
                print(
                    "API does not appear to support response_format; retrying without it.",
                    file=sys.stderr,
                )
                continue
            sleep_seconds = args.retry_sleep * (2**attempt) + random.random()
            print(f"API call failed ({attempt + 1}/{args.max_retries}): {exc}", file=sys.stderr)
            time.sleep(sleep_seconds)
    raise RuntimeError(f"Qwen rerank failed after retries: {last_error}")


def confidence_ok(confidence: str, minimum: str) -> bool:
    rank = {"low": 0, "medium": 1, "high": 2}
    return rank.get(str(confidence).lower(), -1) >= rank[minimum]


def word_count(text: str) -> int:
    return len(text.split())


def len_ratio_ok(chosen: str, rejected: str, min_ratio: float, max_ratio: float) -> bool:
    rejected_len = max(word_count(rejected), 1)
    ratio = word_count(chosen) / rejected_len
    return min_ratio <= ratio <= max_ratio


def add_pair(
    pairs: list[dict[str, Any]],
    seen: set[tuple[str, str]],
    prompt: str,
    chosen: str | None,
    rejected: str | None,
    pair_type: str,
    args: argparse.Namespace,
    apply_filters: bool = True,
) -> None:
    if not chosen or not rejected or chosen.strip() == rejected.strip():
        return
    if apply_filters and word_count(chosen) > args.max_chosen_words:
        return
    if apply_filters and not len_ratio_ok(
        chosen, rejected, args.min_len_ratio, args.max_len_ratio
    ):
        return
    key = (chosen, rejected)
    if key in seen:
        return
    seen.add(key)
    pairs.append(
        {
            "prompt": prompt,
            "chosen": chosen,
            "rejected": rejected,
            "pair_type": pair_type,
        }
    )


def build_dpo_pairs(
    row: dict[str, Any],
    judgment: dict[str, Any],
    args: argparse.Namespace,
) -> list[dict[str, Any]]:
    response_items = build_response_items(row)
    prompt = row.get("prompt", "")
    gold = response_items.get("gold")
    contrastive = response_items.get("contrastive")
    best_sample = str(judgment.get("best_sample", ""))
    worst_sample = str(judgment.get("worst_sample", ""))
    ranking = list(judgment.get("ranking", []))
    bad_candidates = list(judgment.get("bad_candidates", []))
    samples_better_than_gold = set(judgment.get("samples_better_than_gold", []))

    if not gold or not contrastive:
        return []
    if best_sample not in response_items or worst_sample not in response_items:
        return []

    pairs: list[dict[str, Any]] = []
    seen: set[tuple[str, str]] = set()
    rank_pos = {response_id: pos for pos, response_id in enumerate(ranking)}

    add_pair(
        pairs,
        seen,
        prompt,
        gold,
        contrastive,
        "gold_vs_contrastive",
        args,
        apply_filters=False,
    )

    if not confidence_ok(str(judgment.get("confidence", "")).lower(), args.min_confidence):
        return pairs[: args.max_pairs_per_example]

    best_text = response_items[best_sample]
    worst_text = response_items[worst_sample]
    if rank_pos[best_sample] < rank_pos["contrastive"]:
        add_pair(
            pairs,
            seen,
            prompt,
            best_text,
            contrastive,
            "best_sample_vs_contrastive",
            args,
        )

    if rank_pos[best_sample] < rank_pos[worst_sample]:
        add_pair(
            pairs,
            seen,
            prompt,
            best_text,
            worst_text,
            "best_sample_vs_worst_sample",
            args,
        )

    lower_sample_count = 0
    for response_id in ranking[rank_pos[best_sample] + 1 :]:
        if lower_sample_count >= 2:
            break
        if not response_id.startswith("sample_") or response_id == worst_sample:
            continue
        add_pair(
            pairs,
            seen,
            prompt,
            best_text,
            response_items[response_id],
            "best_sample_vs_lower_sample",
            args,
        )
        lower_sample_count += 1
        if len(pairs) >= args.max_pairs_per_example:
            break

    for response_id in bad_candidates:
        if len(pairs) >= args.max_pairs_per_example:
            break
        if rank_pos["gold"] < rank_pos[response_id]:
            add_pair(
                pairs,
                seen,
                prompt,
                gold,
                response_items[response_id],
                "gold_vs_bad_candidate",
                args,
            )

    if args.include_sample_vs_gold:
        for response_id in ranking:
            if len(pairs) >= args.max_pairs_per_example:
                break
            if (
                response_id in samples_better_than_gold
                and rank_pos[response_id] < rank_pos["gold"]
            ):
                add_pair(
                    pairs,
                    seen,
                    prompt,
                    response_items[response_id],
                    gold,
                    "sample_vs_gold",
                    args,
                )

    return pairs[: args.max_pairs_per_example]


def process_row(
    args: argparse.Namespace,
    row: dict[str, Any],
    local_idx: int,
    total_rows: int,
    row_index: int,
    key: str,
) -> dict[str, Any]:
    if not row.get("candidates"):
        return {
            "status": "skipped",
            "local_idx": local_idx,
            "total_rows": total_rows,
            "message": "skip row without candidates",
        }

    response_items = build_response_items(row)
    expected_ids = set(response_items)
    if "gold" not in expected_ids or "contrastive" not in expected_ids:
        return {
            "status": "skipped",
            "local_idx": local_idx,
            "total_rows": total_rows,
            "message": "skip row without gold/contrastive",
        }

    user_prompt = build_user_prompt(row)
    try:
        client = get_thread_client(args)
        judgment = call_judge(client, args, user_prompt, expected_ids)
        pairs = build_dpo_pairs(row, judgment, args)
    except Exception as exc:
        failed_row = dict(row)
        failed_row.update(
            {
                "source_key": key,
                "row_index": row_index,
                "judge_model": args.model,
                "judge_base_url": args.base_url,
                "error": str(exc),
                "max_retries": args.max_retries,
            }
        )
        return {
            "status": "failed",
            "local_idx": local_idx,
            "total_rows": total_rows,
            "failed_row": failed_row,
        }

    rerank_row = dict(row)
    rerank_row.update(
        {
            "source_key": key,
            "row_index": row_index,
            "judge_model": args.model,
            "judge_base_url": args.base_url,
            "judgment": judgment,
            "dpo_pair_count": len(pairs),
        }
    )

    pair_rows = []
    for pair_id, pair in enumerate(pairs, start=1):
        pair_rows.append(
            {
                "source_key": key,
                "row_index": row_index,
                "pair_id": pair_id,
                "judge_model": args.model,
                "Scenario": row.get("Scenario", ""),
                "Question": row.get("Question", ""),
                "Value": row.get("Value", ""),
                **pair,
            }
        )

    return {
        "status": "success",
        "local_idx": local_idx,
        "total_rows": total_rows,
        "rerank_row": rerank_row,
        "pair_rows": pair_rows,
        "pair_count": len(pair_rows),
        "confidence": judgment.get("confidence"),
        "best_sample": judgment.get("best_sample"),
    }


def main() -> None:
    args = parse_args()
    retry_failed = args.retry_failed_file is not None
    input_file = Path(args.retry_failed_file if retry_failed else args.input_file)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    rerank_path = output_dir / "rerank_results.jsonl"
    dpo_path = output_dir / "dpo_pairs.jsonl"
    failed_output_name = args.failed_output_name
    if failed_output_name is None:
        failed_output_name = (
            "failed_samples_retry.jsonl" if retry_failed else "failed_samples.jsonl"
        )
    failed_path = output_dir / failed_output_name
    config_path = output_dir / "run_config.json"

    # Validate API credentials and OpenAI-compatible client import before launching workers.
    make_client(args)
    rows = load_jsonl(input_file, limit=args.limit, start=args.start)
    if args.resume and retry_failed:
        completed = load_completed_keys(rerank_path)
    elif args.resume:
        completed = load_completed_keys(rerank_path, failed_path)
    else:
        completed = set()

    with config_path.open("w", encoding="utf-8") as f:
        json.dump(vars(args), f, ensure_ascii=False, indent=2)
        f.write("\n")

    print(f"Loaded {len(rows)} rows from {input_file}")
    if retry_failed:
        print("Retry-failed mode: preserving source_key and row_index from failed samples")
    print(f"Writing rerank results to {rerank_path}")
    print(f"Writing DPO pairs to {dpo_path}")
    print(f"Writing failed samples to {failed_path}")
    print(f"Concurrent workers: {args.num_workers}")

    total_pairs = 0
    total_failed = 0
    total_skipped = 0
    futures = {}

    with ThreadPoolExecutor(max_workers=args.num_workers) as executor:
        for local_idx, row in enumerate(rows, start=1):
            fallback_row_index = args.start + local_idx - 1
            if retry_failed:
                try:
                    row_index = int(row.get("row_index", fallback_row_index))
                except (TypeError, ValueError):
                    row_index = fallback_row_index
                source_row = clean_input_row(row)
                key = str(row.get("source_key") or source_key(source_row, row_index))
            else:
                row_index = fallback_row_index
                source_row = clean_input_row(row)
                key = source_key(source_row, row_index)
            if key in completed:
                total_skipped += 1
                print(f"[{local_idx}/{len(rows)}] skip completed {key}")
                continue
            futures[
                executor.submit(
                    process_row,
                    args,
                    source_row,
                    local_idx,
                    len(rows),
                    row_index,
                    key,
                )
            ] = key

        for future in as_completed(futures):
            result = future.result()
            status = result["status"]
            local_idx = result["local_idx"]
            total_rows = result["total_rows"]

            if status == "skipped":
                total_skipped += 1
                print(f"[{local_idx}/{total_rows}] {result['message']}", file=sys.stderr)
                continue

            if status == "failed":
                total_failed += 1
                append_jsonl(failed_path, result["failed_row"])
                print(
                    f"[{local_idx}/{total_rows}] failed after {args.max_retries} retries; "
                    f"saved to {failed_path}",
                    file=sys.stderr,
                )
                continue

            append_jsonl(rerank_path, result["rerank_row"])
            for pair_row in result["pair_rows"]:
                append_jsonl(dpo_path, pair_row)
            total_pairs += result["pair_count"]
            print(
                f"[{local_idx}/{total_rows}] pairs={result['pair_count']} "
                f"confidence={result['confidence']} "
                f"best_sample={result['best_sample']}"
            )

    print(f"Done. New DPO pairs written in this run: {total_pairs}")
    print(f"Failed samples in this run: {total_failed}")
    print(f"Skipped samples in this run: {total_skipped}")


if __name__ == "__main__":
    main()
